package com.agaseeyyy.transparencysystem.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.validation.constraints.*;

/**
 * DTO for creating or updating an expense
 */
public class ExpenseInputDTO {
    
    // expenseReference is usually generated by backend, so not validated here if backend generates it
    // If front-end can suggest one, then add @Size for example.
    private String expenseReference;

    @NotBlank(message = "Expense title is required")
    @Size(max = 255, message = "Expense title cannot exceed 255 characters")
    private String expenseTitle;

    @NotNull(message = "Expense category is required")
    private String expenseCategory;

    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than 0")
    private BigDecimal amount;

    @Size(max = 1000, message = "Description cannot exceed 1000 characters")
    private String expenseDescription;

    @Size(max = 255, message = "Vendor/Supplier name cannot exceed 255 characters")
    private String vendorSupplier;

    @Size(max = 100, message = "Receipt/Invoice number cannot exceed 100 characters")
    private String receiptInvoiceNumber;

    @NotNull(message = "Expense date is required")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate expenseDate;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate paymentDate; // Optional, but if present, must be past or present

    private String paymentMethod;

    private String departmentId;

    @NotNull(message = "Related fee is required")
    private String relatedFeeId;

    private String budgetAllocation;

    private Boolean isRecurring = false;

    private String recurringFrequency;

    private String academicYear;

    @NotBlank(message = "Semester is required")
    private String semester;

    private String documentationPath;

    private BigDecimal taxAmount;

    private Boolean isTaxInclusive = false;

    private String remarks;

    // Default constructor
    public ExpenseInputDTO() {}
    
    // Getters and setters
    public String getExpenseReference() {
        return expenseReference;
    }
    
    public void setExpenseReference(String expenseReference) {
        this.expenseReference = expenseReference;
    }
    
    public String getExpenseTitle() {
        return expenseTitle;
    }
    
    public void setExpenseTitle(String expenseTitle) {
        this.expenseTitle = expenseTitle;
    }
    
    public String getExpenseCategory() {
        return expenseCategory;
    }
    
    public void setExpenseCategory(String expenseCategory) {
        this.expenseCategory = expenseCategory;
    }
    
    public BigDecimal getAmount() {
        return amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    public String getExpenseDescription() {
        return expenseDescription;
    }
    
    public void setExpenseDescription(String expenseDescription) {
        this.expenseDescription = expenseDescription;
    }
    
    public String getVendorSupplier() {
        return vendorSupplier;
    }
    
    public void setVendorSupplier(String vendorSupplier) {
        this.vendorSupplier = vendorSupplier;
    }
    
    public String getReceiptInvoiceNumber() {
        return receiptInvoiceNumber;
    }
    
    public void setReceiptInvoiceNumber(String receiptInvoiceNumber) {
        this.receiptInvoiceNumber = receiptInvoiceNumber;
    }
    
    public LocalDate getExpenseDate() {
        return expenseDate;
    }
    
    public void setExpenseDate(LocalDate expenseDate) {
        this.expenseDate = expenseDate;
    }
    
    public LocalDate getPaymentDate() {
        return paymentDate;
    }
    
    public void setPaymentDate(LocalDate paymentDate) {
        this.paymentDate = paymentDate;
    }
    
    public String getPaymentMethod() {
        return paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    
    public String getDepartmentId() {
        return departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    
    public String getRelatedFeeId() {
        return relatedFeeId;
    }
    
    public void setRelatedFeeId(String relatedFeeId) {
        this.relatedFeeId = relatedFeeId;
    }
    
    public String getBudgetAllocation() {
        return budgetAllocation;
    }
    
    public void setBudgetAllocation(String budgetAllocation) {
        this.budgetAllocation = budgetAllocation;
    }
    
    public Boolean getIsRecurring() {
        return isRecurring;
    }
    
    public void setIsRecurring(Boolean isRecurring) {
        this.isRecurring = isRecurring;
    }
    
    public String getRecurringFrequency() {
        return recurringFrequency;
    }
    
    public void setRecurringFrequency(String recurringFrequency) {
        this.recurringFrequency = recurringFrequency;
    }
    
    public String getAcademicYear() {
        return academicYear;
    }
    
    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }
    
    public String getSemester() {
        return semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    
    public String getDocumentationPath() {
        return documentationPath;
    }
    
    public void setDocumentationPath(String documentationPath) {
        this.documentationPath = documentationPath;
    }
    
    public BigDecimal getTaxAmount() {
        return taxAmount;
    }
    
    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }
    
    public Boolean getIsTaxInclusive() {
        return isTaxInclusive;
    }
    
    public void setIsTaxInclusive(Boolean isTaxInclusive) {
        this.isTaxInclusive = isTaxInclusive;
    }
    
    public String getRemarks() {
        return remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}
